### ISSUE TITLE
Implementar US2, US3 e US10

### ISSUE THREAD

**Issue by ericksjp** [ericksjp/MedicalInfo-Java#4]
- Desenvolver um método que calcule a frequência cardíaca máxima do usuário com base em sua idade, a qual é determinada pela sua data de nascimento.

- Desenvolver métodos que calculem a frequência cardíaca alvo mínima e máxima do usuário com base em sua frequência cardíaca máxima.

- Desenvolver um método que calcule a taxa metabólica basal do usuário de acordo com o seu nível de atividade física, gênero, idade, peso e altura.

Implemente na sua branch e mande o link do commit.

**Comment by tassomoreira** [comment]
- **Desenvolvendo o metodo que calcula a frequencia cardiaca maxima** [d3b1b80d5f91eb7ab7ffb7dfad8c394860134]
- **Desenvolvendo o metodo que calcula a faixa de frequencia cardiaca alvo**  [d089568b2a4c6e4bdf8833bab0c0df6020f08d44]
- **Desenvolvendo o metodo que calcula a taxa metabolica basal [deaf79180baac901f3cd0ffbd1f46c14f1fe06b3]**
