### ISSUE TITLE
Implementar US5, US6 e US7

### ISSUE THREAD

**Issue by ericksjp** [ericksjp/MedicalInfo-Java#5]
- Desenvolver um método que imprima uma tabela de referência com todas as faixas de IMC.
- Desenvolver um método que calcule a quantidade recomendada de água que deve ser ingerida pelo usuário de acordo com
a fórmula especificada.
- Desenvolver um método que calcule a taxa de gordura corporal (BT) do usuário de acordo com a fórmula especificada.

Implemente na sua branch e mande o link do commit.

**Comment by GerlandioBernardo** [comment]
b49ae58e5e215809b2694aac956cd0cce83ace7c

**Comment by ericksjp** [comment]
e954a9af4b70e5b54e94633f026686e153cb2ef2
